/**
* @author Cliff Ng
* @version 1.0, 5/11/2019
*/

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;


public class TierOneSortByDuration {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void parisToMadrid270918() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1536, 824));
        driver.findElement(By.cssSelector("form:nth-child(1)")).click();
        driver.findElement(By.id("departure")).clear();
        driver.findElement(By.id("departure")).sendKeys("Paris - Charles De Gaulle, France");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        driver.findElement(By.id("arrival")).clear();
        driver.findElement(By.id("arrival")).sendKeys("Madrid, Spain");
        driver.findElement(By.cssSelector(".container:nth-child(3)")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("input:nth-child(1)")).click();

        WebElement priceSlider = driver.findElement(By.name("priceWeight"));
        WebElement durationSlider = driver.findElement(By.name("durationWeight"));
        WebElement ratingSlider = driver.findElement(By.name("ratingWeight"));
        WebElement noStopOversSlider = driver.findElement(By.name("noStopOversWeight"));

        for (int i = 1; i <= 4 ; i++) {
            priceSlider.sendKeys(Keys.ARROW_LEFT);
            durationSlider.sendKeys(Keys.ARROW_LEFT);
            ratingSlider.sendKeys(Keys.ARROW_LEFT);
            noStopOversSlider.sendKeys(Keys.ARROW_LEFT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }


        driver.findElement(By.name("submit")).click();

        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("form:nth-child(6) > input")).sendKeys(Keys.RETURN);

        WebElement durationSliderAfter = driver.findElement(By.name("durationWeight"));

        for (int i = 1; i <= 4 ; i++) {
            durationSliderAfter.sendKeys(Keys.ARROW_RIGHT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        driver.findElement(By.name("submit")).click();
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void cairnsToHobart270218() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1536, 824));
        driver.findElement(By.cssSelector("form:nth-child(1)")).click();
        driver.findElement(By.id("departure")).clear();
        driver.findElement(By.id("departure")).sendKeys("Cairns, Australia");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        driver.findElement(By.id("arrival")).clear();
        driver.findElement(By.id("arrival")).sendKeys("Hobart, Australia");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        driver.findElement(By.id("departuredate")).click();
        driver.findElement(By.id("departuredate")).clear();
        driver.findElement(By.id("departuredate")).sendKeys("27/02/2018");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("input:nth-child(1)")).click();

        WebElement priceSlider = driver.findElement(By.name("priceWeight"));
        WebElement durationSlider = driver.findElement(By.name("durationWeight"));
        WebElement ratingSlider = driver.findElement(By.name("ratingWeight"));
        WebElement noStopOversSlider = driver.findElement(By.name("noStopOversWeight"));

        for (int i = 1; i <= 4 ; i++) {
            priceSlider.sendKeys(Keys.ARROW_LEFT);
            durationSlider.sendKeys(Keys.ARROW_LEFT);
            ratingSlider.sendKeys(Keys.ARROW_LEFT);
            noStopOversSlider.sendKeys(Keys.ARROW_LEFT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }


        driver.findElement(By.name("submit")).click();

        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("form:nth-child(6) > input")).sendKeys(Keys.RETURN);

        WebElement durationSliderAfter = driver.findElement(By.name("durationWeight"));

        for (int i = 1; i <= 4 ; i++) {
            durationSliderAfter.sendKeys(Keys.ARROW_RIGHT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        driver.findElement(By.name("submit")).click();
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void laToNY220917() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1536, 824));
        driver.findElement(By.cssSelector("form:nth-child(1)")).click();
        driver.findElement(By.id("departure")).clear();
        driver.findElement(By.id("departure")).sendKeys("Los Angeles, United States");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        driver.findElement(By.id("arrival")).clear();
        driver.findElement(By.id("arrival")).sendKeys("New York - JFK, United States");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        driver.findElement(By.id("departuredate")).click();
        driver.findElement(By.id("departuredate")).clear();
        driver.findElement(By.id("departuredate")).sendKeys("22/09/2017");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("input:nth-child(1)")).click();

        WebElement priceSlider = driver.findElement(By.name("priceWeight"));
        WebElement durationSlider = driver.findElement(By.name("durationWeight"));
        WebElement ratingSlider = driver.findElement(By.name("ratingWeight"));
        WebElement noStopOversSlider = driver.findElement(By.name("noStopOversWeight"));

        for (int i = 1; i <= 4 ; i++) {
            priceSlider.sendKeys(Keys.ARROW_LEFT);
            durationSlider.sendKeys(Keys.ARROW_LEFT);
            ratingSlider.sendKeys(Keys.ARROW_LEFT);
            noStopOversSlider.sendKeys(Keys.ARROW_LEFT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }


        driver.findElement(By.name("submit")).click();

        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("form:nth-child(6) > input")).sendKeys(Keys.RETURN);

        WebElement durationSliderAfter = driver.findElement(By.name("durationWeight"));

        for (int i = 1; i <= 4 ; i++) {
            durationSliderAfter.sendKeys(Keys.ARROW_RIGHT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        driver.findElement(By.name("submit")).click();
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void adelaideToMelbourne() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1536, 824));
        driver.findElement(By.cssSelector("form:nth-child(1)")).click();
        driver.findElement(By.id("departure")).clear();
        driver.findElement(By.id("departure")).sendKeys("Adelaide, Australia");
        driver.findElement(By.cssSelector(".container:nth-child(2) > .row:nth-child(1)")).click();
        driver.findElement(By.id("arrival")).clear();
        driver.findElement(By.id("arrival")).sendKeys("Melbourne, Australia");
        driver.findElement(By.cssSelector(".container:nth-child(3)")).click();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("input:nth-child(1)")).click();

        WebElement priceSlider = driver.findElement(By.name("priceWeight"));
        WebElement durationSlider = driver.findElement(By.name("durationWeight"));
        WebElement ratingSlider = driver.findElement(By.name("ratingWeight"));
        WebElement noStopOversSlider = driver.findElement(By.name("noStopOversWeight"));

        for (int i = 1; i <= 4 ; i++) {
            priceSlider.sendKeys(Keys.ARROW_LEFT);
            durationSlider.sendKeys(Keys.ARROW_LEFT);
            ratingSlider.sendKeys(Keys.ARROW_LEFT);
            noStopOversSlider.sendKeys(Keys.ARROW_LEFT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }


        driver.findElement(By.name("submit")).click();

        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("form:nth-child(6) > input")).sendKeys(Keys.RETURN);

        WebElement durationSliderAfter = driver.findElement(By.name("durationWeight"));

        for (int i = 1; i <= 4 ; i++) {
            durationSliderAfter.sendKeys(Keys.ARROW_RIGHT);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        driver.findElement(By.name("submit")).click();
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

}
